
POST http://127.0.0.1:4700/students
Content-Type: application/json

{
    "id" : 3,
    "name": "Jenna",
    "grade" : "12th",
    "fees": "3000"
}

### GET ALL PROJECTS
GET http://localhost:4700/students


### GET ONE PROJECT
GET http://localhost:4700/students/3

### UPDATING PROJECT
PUT http://localhost:4700/students/1
Content-Type: application/json
{
    "id" : 1,
    "name": "James",
    "grade" : "11th",
    "fees": "2000"
}
###
DELETE http://localhost:4700/students/5




